# stellar.toml
FEDERATION_SERVER="https://example.com/federation"
AUTH_SERVER="https://example.com/auth"
ACCOUNTS=["GAFWIHVVGHFOHOD7DABE5TBOVE6JYOKO7DKYPCOCH5QYBTAYDRCVURD4"]

[[CURRENCIES]]
code="USD"
issuer="GAKP4XCSVPWUYQCK2VD3DMZ7AP5ATPN2VBJMFPLVTJGMAYR53KDXZBXY"
display_decimals=2
